menus:
    HOME: /
    PHOTOGRAPHY: https://unsplash.com/@dabanli
    GITHUB: https://github.com/dabanlee

favicon: /favicon.png
logo: /images/logo.jpg
title: Lee
description: ''
url: /
urls: http://dabanlee.github.io/
startyear: 2015
thisyear: 2025
